name: Integration Test Pull Request
on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest-8core
    if: |
      github.actor == 'renovate[bot]' ||
      github.actor == 'dependabot[bot]' ||
      contains(github.event.pull_request.title, 'run-int-tests') ||
      contains(github.event.head_commit.message, 'run-int-tests')

    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6
        with:
          go-version-file: go.mod

      - name: make revendor
        run: make revendor

      - name: make build
        run: make build

      - name: run integration test
        env:
          GARDENER_KUBECONFIG: ${{ secrets.GARDENER_LAAS_SERVICE_ACCOUNT }}
          PULL_REQUEST_ID: ${{ github.event.pull_request.number }}
        run: |
          VERSION="$('./hack/get-version.sh')"
          "./hack/integration-test-runner.sh" "$GARDENER_KUBECONFIG" "garden-laas" "$VERSION" "$PULL_REQUEST_ID"
